### ISSUE TITLE
Great demo! Some small bugs...

### ISSUE THREAD

**Issue by MoralCode** [Buglife/Buglife-iOS-Demo#1]
![image](https://cloud.githubusercontent.com/assets/17362949/13814967/e631c672-eb45-11e5-991b-497303032dd5.png)

![image](https://cloud.githubusercontent.com/assets/17362949/13814976/f2fc37d4-eb45-11e5-86f0-ddf9c7eff274.png)

Should be self-explanatory...

**Comment by MoralCode** [comment]
Also, I had an idea. Add GitHub integration so submitted bugs appear in issues on GitHub.

**Comment by MoralCode** [comment]
Oh and you should add an option to not send a screenshot in cases where it isn't needed...

Sorry, I just have so many ideas. This looks like an excellent start to an amazing product

**Comment by schukin** [comment]
Thanks for reporting this! We've fixed this issue in the latest version of the Buglife SDK (v1.0.2). GitHub integration is coming soon, stay tuned.

And no need to apologize, we love hearing your ideas! :sunglasses:

**Comment by MoralCode** [comment]
how do you adjust the position of the little buglife icon?

**Comment by schukin** [comment]
Hey @DeveloperACE - Users can touch & drag the Buglife button around the screen. The last location of the button is remembered between app launches.

**Comment by MoralCode** [comment]
Cool! Did not know that... Is there a way to programmatically fix the button in place or otherwise set its default position?

**Comment by schukin** [comment]
At the moment we don't provide a way to programmatically set the button position.
